// Generated by gencpp from file session_one/CustomServiceMessage.msg
// DO NOT EDIT!


#ifndef SESSION_ONE_MESSAGE_CUSTOMSERVICEMESSAGE_H
#define SESSION_ONE_MESSAGE_CUSTOMSERVICEMESSAGE_H

#include <ros/service_traits.h>


#include <session_one/CustomServiceMessageRequest.h>
#include <session_one/CustomServiceMessageResponse.h>


namespace session_one
{

struct CustomServiceMessage
{

typedef CustomServiceMessageRequest Request;
typedef CustomServiceMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CustomServiceMessage
} // namespace session_one


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::session_one::CustomServiceMessage > {
  static const char* value()
  {
    return "614144eb549744facbf2977736dcf7b9";
  }

  static const char* value(const ::session_one::CustomServiceMessage&) { return value(); }
};

template<>
struct DataType< ::session_one::CustomServiceMessage > {
  static const char* value()
  {
    return "session_one/CustomServiceMessage";
  }

  static const char* value(const ::session_one::CustomServiceMessage&) { return value(); }
};


// service_traits::MD5Sum< ::session_one::CustomServiceMessageRequest> should match
// service_traits::MD5Sum< ::session_one::CustomServiceMessage >
template<>
struct MD5Sum< ::session_one::CustomServiceMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::session_one::CustomServiceMessage >::value();
  }
  static const char* value(const ::session_one::CustomServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::session_one::CustomServiceMessageRequest> should match
// service_traits::DataType< ::session_one::CustomServiceMessage >
template<>
struct DataType< ::session_one::CustomServiceMessageRequest>
{
  static const char* value()
  {
    return DataType< ::session_one::CustomServiceMessage >::value();
  }
  static const char* value(const ::session_one::CustomServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::session_one::CustomServiceMessageResponse> should match
// service_traits::MD5Sum< ::session_one::CustomServiceMessage >
template<>
struct MD5Sum< ::session_one::CustomServiceMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::session_one::CustomServiceMessage >::value();
  }
  static const char* value(const ::session_one::CustomServiceMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::session_one::CustomServiceMessageResponse> should match
// service_traits::DataType< ::session_one::CustomServiceMessage >
template<>
struct DataType< ::session_one::CustomServiceMessageResponse>
{
  static const char* value()
  {
    return DataType< ::session_one::CustomServiceMessage >::value();
  }
  static const char* value(const ::session_one::CustomServiceMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SESSION_ONE_MESSAGE_CUSTOMSERVICEMESSAGE_H
