// Generated by gencpp from file session_one/CustomServiceMessageResponse.msg
// DO NOT EDIT!


#ifndef SESSION_ONE_MESSAGE_CUSTOMSERVICEMESSAGERESPONSE_H
#define SESSION_ONE_MESSAGE_CUSTOMSERVICEMESSAGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace session_one
{
template <class ContainerAllocator>
struct CustomServiceMessageResponse_
{
  typedef CustomServiceMessageResponse_<ContainerAllocator> Type;

  CustomServiceMessageResponse_()
    : distanceIndices()  {
    }
  CustomServiceMessageResponse_(const ContainerAllocator& _alloc)
    : distanceIndices(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _distanceIndices_type;
  _distanceIndices_type distanceIndices;





  typedef boost::shared_ptr< ::session_one::CustomServiceMessageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::session_one::CustomServiceMessageResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CustomServiceMessageResponse_

typedef ::session_one::CustomServiceMessageResponse_<std::allocator<void> > CustomServiceMessageResponse;

typedef boost::shared_ptr< ::session_one::CustomServiceMessageResponse > CustomServiceMessageResponsePtr;
typedef boost::shared_ptr< ::session_one::CustomServiceMessageResponse const> CustomServiceMessageResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::session_one::CustomServiceMessageResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::session_one::CustomServiceMessageResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::session_one::CustomServiceMessageResponse_<ContainerAllocator1> & lhs, const ::session_one::CustomServiceMessageResponse_<ContainerAllocator2> & rhs)
{
  return lhs.distanceIndices == rhs.distanceIndices;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::session_one::CustomServiceMessageResponse_<ContainerAllocator1> & lhs, const ::session_one::CustomServiceMessageResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace session_one

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::session_one::CustomServiceMessageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::session_one::CustomServiceMessageResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::session_one::CustomServiceMessageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::session_one::CustomServiceMessageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::session_one::CustomServiceMessageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::session_one::CustomServiceMessageResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::session_one::CustomServiceMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "614144eb549744facbf2977736dcf7b9";
  }

  static const char* value(const ::session_one::CustomServiceMessageResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x614144eb549744faULL;
  static const uint64_t static_value2 = 0xcbf2977736dcf7b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::session_one::CustomServiceMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "session_one/CustomServiceMessageResponse";
  }

  static const char* value(const ::session_one::CustomServiceMessageResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::session_one::CustomServiceMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] distanceIndices\n"
"\n"
;
  }

  static const char* value(const ::session_one::CustomServiceMessageResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::session_one::CustomServiceMessageResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distanceIndices);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomServiceMessageResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::session_one::CustomServiceMessageResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::session_one::CustomServiceMessageResponse_<ContainerAllocator>& v)
  {
    s << indent << "distanceIndices[]" << std::endl;
    for (size_t i = 0; i < v.distanceIndices.size(); ++i)
    {
      s << indent << "  distanceIndices[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.distanceIndices[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SESSION_ONE_MESSAGE_CUSTOMSERVICEMESSAGERESPONSE_H
