(cl:defpackage session_one-srv
  (:use )
  (:export
   "CUSTOMSERVICEMESSAGE"
   "<CUSTOMSERVICEMESSAGE-REQUEST>"
   "CUSTOMSERVICEMESSAGE-REQUEST"
   "<CUSTOMSERVICEMESSAGE-RESPONSE>"
   "CUSTOMSERVICEMESSAGE-RESPONSE"
  ))

