// Generated by gencpp from file as_assignment/odomDataGoal.msg
// DO NOT EDIT!


#ifndef AS_ASSIGNMENT_MESSAGE_ODOMDATAGOAL_H
#define AS_ASSIGNMENT_MESSAGE_ODOMDATAGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace as_assignment
{
template <class ContainerAllocator>
struct odomDataGoal_
{
  typedef odomDataGoal_<ContainerAllocator> Type;

  odomDataGoal_()
    : seconds(0)  {
    }
  odomDataGoal_(const ContainerAllocator& _alloc)
    : seconds(0)  {
  (void)_alloc;
    }



   typedef int32_t _seconds_type;
  _seconds_type seconds;





  typedef boost::shared_ptr< ::as_assignment::odomDataGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::as_assignment::odomDataGoal_<ContainerAllocator> const> ConstPtr;

}; // struct odomDataGoal_

typedef ::as_assignment::odomDataGoal_<std::allocator<void> > odomDataGoal;

typedef boost::shared_ptr< ::as_assignment::odomDataGoal > odomDataGoalPtr;
typedef boost::shared_ptr< ::as_assignment::odomDataGoal const> odomDataGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::as_assignment::odomDataGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::as_assignment::odomDataGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::as_assignment::odomDataGoal_<ContainerAllocator1> & lhs, const ::as_assignment::odomDataGoal_<ContainerAllocator2> & rhs)
{
  return lhs.seconds == rhs.seconds;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::as_assignment::odomDataGoal_<ContainerAllocator1> & lhs, const ::as_assignment::odomDataGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace as_assignment

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::as_assignment::odomDataGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::as_assignment::odomDataGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::as_assignment::odomDataGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::as_assignment::odomDataGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::as_assignment::odomDataGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::as_assignment::odomDataGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::as_assignment::odomDataGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7185940bcec4e3e995419aeb77a0ca23";
  }

  static const char* value(const ::as_assignment::odomDataGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7185940bcec4e3e9ULL;
  static const uint64_t static_value2 = 0x95419aeb77a0ca23ULL;
};

template<class ContainerAllocator>
struct DataType< ::as_assignment::odomDataGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "as_assignment/odomDataGoal";
  }

  static const char* value(const ::as_assignment::odomDataGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::as_assignment::odomDataGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#Goal\n"
"int32 seconds\n"
;
  }

  static const char* value(const ::as_assignment::odomDataGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::as_assignment::odomDataGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.seconds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct odomDataGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::as_assignment::odomDataGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::as_assignment::odomDataGoal_<ContainerAllocator>& v)
  {
    s << indent << "seconds: ";
    Printer<int32_t>::stream(s, indent + "  ", v.seconds);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AS_ASSIGNMENT_MESSAGE_ODOMDATAGOAL_H
