(cl:defpackage custom_service_assignment-srv
  (:use )
  (:export
   "SERVICEMESSAGECUSTOM"
   "<SERVICEMESSAGECUSTOM-REQUEST>"
   "SERVICEMESSAGECUSTOM-REQUEST"
   "<SERVICEMESSAGECUSTOM-RESPONSE>"
   "SERVICEMESSAGECUSTOM-RESPONSE"
  ))

