// Generated by gencpp from file compound_assignment/CustomServiceMessageResponse.msg
// DO NOT EDIT!


#ifndef COMPOUND_ASSIGNMENT_MESSAGE_CUSTOMSERVICEMESSAGERESPONSE_H
#define COMPOUND_ASSIGNMENT_MESSAGE_CUSTOMSERVICEMESSAGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace compound_assignment
{
template <class ContainerAllocator>
struct CustomServiceMessageResponse_
{
  typedef CustomServiceMessageResponse_<ContainerAllocator> Type;

  CustomServiceMessageResponse_()
    {
    }
  CustomServiceMessageResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::compound_assignment::CustomServiceMessageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::compound_assignment::CustomServiceMessageResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CustomServiceMessageResponse_

typedef ::compound_assignment::CustomServiceMessageResponse_<std::allocator<void> > CustomServiceMessageResponse;

typedef boost::shared_ptr< ::compound_assignment::CustomServiceMessageResponse > CustomServiceMessageResponsePtr;
typedef boost::shared_ptr< ::compound_assignment::CustomServiceMessageResponse const> CustomServiceMessageResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::compound_assignment::CustomServiceMessageResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::compound_assignment::CustomServiceMessageResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace compound_assignment

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::compound_assignment::CustomServiceMessageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::compound_assignment::CustomServiceMessageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::compound_assignment::CustomServiceMessageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::compound_assignment::CustomServiceMessageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::compound_assignment::CustomServiceMessageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::compound_assignment::CustomServiceMessageResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::compound_assignment::CustomServiceMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::compound_assignment::CustomServiceMessageResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::compound_assignment::CustomServiceMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "compound_assignment/CustomServiceMessageResponse";
  }

  static const char* value(const ::compound_assignment::CustomServiceMessageResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::compound_assignment::CustomServiceMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
;
  }

  static const char* value(const ::compound_assignment::CustomServiceMessageResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::compound_assignment::CustomServiceMessageResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomServiceMessageResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::compound_assignment::CustomServiceMessageResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::compound_assignment::CustomServiceMessageResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // COMPOUND_ASSIGNMENT_MESSAGE_CUSTOMSERVICEMESSAGERESPONSE_H
