// Generated by gencpp from file custom_service_assignment/ServiceMessageCustom.msg
// DO NOT EDIT!


#ifndef CUSTOM_SERVICE_ASSIGNMENT_MESSAGE_SERVICEMESSAGECUSTOM_H
#define CUSTOM_SERVICE_ASSIGNMENT_MESSAGE_SERVICEMESSAGECUSTOM_H

#include <ros/service_traits.h>


#include <custom_service_assignment/ServiceMessageCustomRequest.h>
#include <custom_service_assignment/ServiceMessageCustomResponse.h>


namespace custom_service_assignment
{

struct ServiceMessageCustom
{

typedef ServiceMessageCustomRequest Request;
typedef ServiceMessageCustomResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServiceMessageCustom
} // namespace custom_service_assignment


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_service_assignment::ServiceMessageCustom > {
  static const char* value()
  {
    return "c2eabfe6ce564bbb0d6ec06a2b02df2d";
  }

  static const char* value(const ::custom_service_assignment::ServiceMessageCustom&) { return value(); }
};

template<>
struct DataType< ::custom_service_assignment::ServiceMessageCustom > {
  static const char* value()
  {
    return "custom_service_assignment/ServiceMessageCustom";
  }

  static const char* value(const ::custom_service_assignment::ServiceMessageCustom&) { return value(); }
};


// service_traits::MD5Sum< ::custom_service_assignment::ServiceMessageCustomRequest> should match
// service_traits::MD5Sum< ::custom_service_assignment::ServiceMessageCustom >
template<>
struct MD5Sum< ::custom_service_assignment::ServiceMessageCustomRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_service_assignment::ServiceMessageCustom >::value();
  }
  static const char* value(const ::custom_service_assignment::ServiceMessageCustomRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_service_assignment::ServiceMessageCustomRequest> should match
// service_traits::DataType< ::custom_service_assignment::ServiceMessageCustom >
template<>
struct DataType< ::custom_service_assignment::ServiceMessageCustomRequest>
{
  static const char* value()
  {
    return DataType< ::custom_service_assignment::ServiceMessageCustom >::value();
  }
  static const char* value(const ::custom_service_assignment::ServiceMessageCustomRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_service_assignment::ServiceMessageCustomResponse> should match
// service_traits::MD5Sum< ::custom_service_assignment::ServiceMessageCustom >
template<>
struct MD5Sum< ::custom_service_assignment::ServiceMessageCustomResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_service_assignment::ServiceMessageCustom >::value();
  }
  static const char* value(const ::custom_service_assignment::ServiceMessageCustomResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_service_assignment::ServiceMessageCustomResponse> should match
// service_traits::DataType< ::custom_service_assignment::ServiceMessageCustom >
template<>
struct DataType< ::custom_service_assignment::ServiceMessageCustomResponse>
{
  static const char* value()
  {
    return DataType< ::custom_service_assignment::ServiceMessageCustom >::value();
  }
  static const char* value(const ::custom_service_assignment::ServiceMessageCustomResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_SERVICE_ASSIGNMENT_MESSAGE_SERVICEMESSAGECUSTOM_H
