// Generated by gencpp from file custom_service_assignment/ServiceMessageCustomResponse.msg
// DO NOT EDIT!


#ifndef CUSTOM_SERVICE_ASSIGNMENT_MESSAGE_SERVICEMESSAGECUSTOMRESPONSE_H
#define CUSTOM_SERVICE_ASSIGNMENT_MESSAGE_SERVICEMESSAGECUSTOMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_service_assignment
{
template <class ContainerAllocator>
struct ServiceMessageCustomResponse_
{
  typedef ServiceMessageCustomResponse_<ContainerAllocator> Type;

  ServiceMessageCustomResponse_()
    : success(false)
    , info()  {
    }
  ServiceMessageCustomResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , info(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ServiceMessageCustomResponse_

typedef ::custom_service_assignment::ServiceMessageCustomResponse_<std::allocator<void> > ServiceMessageCustomResponse;

typedef boost::shared_ptr< ::custom_service_assignment::ServiceMessageCustomResponse > ServiceMessageCustomResponsePtr;
typedef boost::shared_ptr< ::custom_service_assignment::ServiceMessageCustomResponse const> ServiceMessageCustomResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator1> & lhs, const ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.info == rhs.info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator1> & lhs, const ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_service_assignment

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "978591831993dbbd56334a367ff288ff";
  }

  static const char* value(const ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x978591831993dbbdULL;
  static const uint64_t static_value2 = 0x56334a367ff288ffULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_service_assignment/ServiceMessageCustomResponse";
  }

  static const char* value(const ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"char[] info\n"
;
  }

  static const char* value(const ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServiceMessageCustomResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_service_assignment::ServiceMessageCustomResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "info[]" << std::endl;
    for (size_t i = 0; i < v.info.size(); ++i)
    {
      s << indent << "  info[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.info[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_SERVICE_ASSIGNMENT_MESSAGE_SERVICEMESSAGECUSTOMRESPONSE_H
