(cl:defpackage compound_assignment-msg
  (:use )
  (:export
   "<ODOMDATAACTION>"
   "ODOMDATAACTION"
   "<ODOMDATAACTIONFEEDBACK>"
   "ODOMDATAACTIONFEEDBACK"
   "<ODOMDATAACTIONGOAL>"
   "ODOMDATAACTIONGOAL"
   "<ODOMDATAACTIONRESULT>"
   "ODOMDATAACTIONRESULT"
   "<ODOMDATAFEEDBACK>"
   "ODOMDATAFEEDBACK"
   "<ODOMDATAGOAL>"
   "ODOMDATAGOAL"
   "<ODOMDATARESULT>"
   "ODOMDATARESULT"
  ))

