; Auto-generated. Do not edit!


(cl:in-package compound_assignment-msg)


;//! \htmlinclude odomDataResult.msg.html

(cl:defclass <odomDataResult> (roslisp-msg-protocol:ros-message)
  ((allValues
    :reader allValues
    :initarg :allValues
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass odomDataResult (<odomDataResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <odomDataResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'odomDataResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name compound_assignment-msg:<odomDataResult> is deprecated: use compound_assignment-msg:odomDataResult instead.")))

(cl:ensure-generic-function 'allValues-val :lambda-list '(m))
(cl:defmethod allValues-val ((m <odomDataResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader compound_assignment-msg:allValues-val is deprecated.  Use compound_assignment-msg:allValues instead.")
  (allValues m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <odomDataResult>) ostream)
  "Serializes a message object of type '<odomDataResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'allValues))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'allValues))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <odomDataResult>) istream)
  "Deserializes a message object of type '<odomDataResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'allValues) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'allValues)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<odomDataResult>)))
  "Returns string type for a message object of type '<odomDataResult>"
  "compound_assignment/odomDataResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'odomDataResult)))
  "Returns string type for a message object of type 'odomDataResult"
  "compound_assignment/odomDataResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<odomDataResult>)))
  "Returns md5sum for a message object of type '<odomDataResult>"
  "fba7c61a9c778bd68f00b7397f54694c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'odomDataResult)))
  "Returns md5sum for a message object of type 'odomDataResult"
  "fba7c61a9c778bd68f00b7397f54694c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<odomDataResult>)))
  "Returns full string definition for message of type '<odomDataResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Result~%float32[] allValues~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'odomDataResult)))
  "Returns full string definition for message of type 'odomDataResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Result~%float32[] allValues~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <odomDataResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'allValues) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <odomDataResult>))
  "Converts a ROS message object to a list"
  (cl:list 'odomDataResult
    (cl:cons ':allValues (allValues msg))
))
